### ISSUE TITLE
delete saved rolls

### ISSUE THREAD

**Issue by jacostag** [babua/RollGramBot#2]
Thanks a lot for the quick response and even faster implementation.
Can you add the option to delete the saved rolls?
Nice touch the WOD dices :D
I do not know if it is too much, but it would be great to save/modify character stats, (strg, dex, wis, etc)
HP and AC would be also be great to show, save, modify. Like @character hp -10/+10

Best regards

**Comment by babua** [comment]
My pleasure :) You're right about the delete feature, it was on my mind too. It was a quick add so it's up and running now.

For the other requests: I'll try to decide the best way to implement them and see if there's a way to do it without being bloat-y. I'll let you know in the coming days :)

**Comment by babua** [comment]
Closed by mistake
